parameters:
  guestbook.entries_per_page:  5

services:
   guestbook_manager:
      class:     AppBundle\Service\GuestbookManager
      arguments: [ '%guestbook.entries_per_page%','@doctrine.orm.entity_manager']
   login_manager:
      class:     AppBundle\Service\LoginManager
      arguments: [ '@service_container','@doctrine.orm.entity_manager' ]
   css_extension:
      class:     AppBundle\Twig\CssExtension
      public:    false
      arguments: [ '@session', '%kernel.root_dir%' ]
      tags:
        - { name: twig.extension }